core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
credential.helper=manager
user.name=Miguel Ureta
user.email=miguelblanco.ureta@benilde.edu.ph
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
pull.rebase=false
core.editor="C:\Users\Mico\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
diff.tool=vsdiffmerge
difftool.prompt=true
difftool.vsdiffmerge.cmd="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsdiffmerge.exe" "$LOCAL" "$REMOTE" //t
difftool.vsdiffmerge.keepbackup=false
merge.tool=vsdiffmerge
mergetool.prompt=true
mergetool.vsdiffmerge.cmd="C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsdiffmerge.exe" "$REMOTE" "$LOCAL" "$BASE" "$MERGED" //m
mergetool.vsdiffmerge.keepbackup=false
mergetool.vsdiffmerge.trustexitcode=true
remote.origin.url=https://github.com/miguelureta/IkapatigiCapstone.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.testbranch.remote=origin
branch.testbranch.merge=refs/heads/testbranch
branch.GabGoogleLogin.2.remote=origin
branch.GabGoogleLogin.2.merge=refs/heads/GabGoogleLogin.2
branch.MicoGoogleLoginTest.remote=origin
branch.MicoGoogleLoginTest.merge=refs/heads/MicoGoogleLoginTest
branch.DiagnosticAdmin.remote=origin
branch.DiagnosticAdmin.merge=refs/heads/DiagnosticAdmin
branch.IdentityBranhc.remote=origin
branch.IdentityBranhc.merge=refs/heads/IdentityBranhc
branch.DiagnosticAdmin-HowTos.remote=origin
branch.DiagnosticAdmin-HowTos.merge=refs/heads/DiagnosticAdmin-HowTos
branch.Expert-HowTos.remote=origin
branch.Expert-HowTos.merge=refs/heads/Expert-HowTos
branch.Diagnostic-HowTos-Forum.remote=origin
branch.Diagnostic-HowTos-Forum.merge=refs/heads/Diagnostic-HowTos-Forum
