// <auto-generated />
using System;
using IkapatigiCapstone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkapatigiCapstone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221115153716_Final Migration")]
    partial class FinalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IkapatigiCapstone.Models.AddRequestDiagnostic", b =>
                {
                    b.Property<int>("AddRequestDiagnosticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AddRequestDiagnosticID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddRequestDiagnosticId"), 1L, 1);

                    b.Property<int?>("ApprovedUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovedUserID");

                    b.Property<string>("CureName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime");

                    b.Property<string>("DiseaseName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RequestedUserId")
                        .HasColumnType("int")
                        .HasColumnName("RequestedUserID");

                    b.Property<decimal?>("Srp")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("SRP");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AddRequestDiagnosticId");

                    b.HasIndex("RequestedUserId");

                    b.ToTable("AddRequestDiagnostics");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Cure", b =>
                {
                    b.Property<int>("CureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CureID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CureId"), 1L, 1);

                    b.Property<string>("CureName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<decimal>("Srp")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("SRP");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CureId");

                    b.ToTable("Cures");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Diagnostic", b =>
                {
                    b.Property<int>("DiagnosticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiagnosticsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosticsId"), 1L, 1);

                    b.Property<int?>("CureId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("CureID");

                    b.Property<int?>("PictureCollectionFromId")
                        .HasColumnType("int")
                        .HasColumnName("PictureCollectionFromID");

                    b.Property<int?>("PlantDiseaseId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("PlantDiseaseID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("TagId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.HasKey("DiagnosticsId")
                        .HasName("PK_Diagnostics_1");

                    b.HasIndex("CureId");

                    b.HasIndex("PlantDiseaseId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TagId");

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Forum", b =>
                {
                    b.Property<int>("ForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumId"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("Forum", (string)null);
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.HowTo", b =>
                {
                    b.Property<int>("HowTosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HowTosID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HowTosID"), 1L, 1);

                    b.Property<string>("ArticleBody")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("IsPublic")
                        .HasColumnType("int");

                    b.Property<int?>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("PictureCollectionFromID")
                        .HasColumnType("int")
                        .HasColumnName("PictureCollectionFromID");

                    b.Property<int?>("StatusID")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("HowTosID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserID");

                    b.ToTable("HowTos");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.PlantDisease", b =>
                {
                    b.Property<int>("PlantDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlantDiseaseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantDiseaseId"), 1L, 1);

                    b.Property<int?>("CureId")
                        .HasColumnType("int")
                        .HasColumnName("CureID");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("ImageOfDisease")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PlantDiseaseId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("PlantDiseases");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PostId");

                    b.HasIndex("ForumId");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.PostReply", b =>
                {
                    b.Property<int>("PostReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostReplyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostReplyId"), 1L, 1);

                    b.Property<string>("Content")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PostReplyId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReply", (string)null);
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Role1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"), 1L, 1);

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("StatusId");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"), 1L, 1);

                    b.Property<string>("TagName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<int?>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("CanceledSubscription")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("RemainingSubscriptionDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.AddRequestDiagnostic", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.User", "RequestedUser")
                        .WithMany("AddRequestDiagnostics")
                        .HasForeignKey("RequestedUserId")
                        .HasConstraintName("FK_AddRequestDiagnostics_Users");

                    b.Navigation("RequestedUser");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Diagnostic", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Cure", "Cure")
                        .WithMany("Diagnostics")
                        .HasForeignKey("CureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Diagnostics_Cures");

                    b.HasOne("IkapatigiCapstone.Models.PlantDisease", "PlantDisease")
                        .WithMany("Diagnostics")
                        .HasForeignKey("PlantDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Diagnostics_PlantDiseases");

                    b.HasOne("IkapatigiCapstone.Models.Status", "Status")
                        .WithMany("Diagnostics")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Diagnostics_Status");

                    b.HasOne("IkapatigiCapstone.Models.Tag", "Tag")
                        .WithMany("Diagnostics")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Diagnostics_Tags");

                    b.Navigation("Cure");

                    b.Navigation("PlantDisease");

                    b.Navigation("Status");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Forum", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("Forums")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Forum_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.HowTo", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Status", "Status")
                        .WithMany("HowTos")
                        .HasForeignKey("StatusID")
                        .HasConstraintName("FK_HowTos_Status");

                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("HowTos")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_HowTos_Users");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.PlantDisease", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Tag", "Tag")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("TagId")
                        .HasConstraintName("FK_PlantDiseases_Tags");

                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PlantDiseases_Users");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Post", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Forum", "Forum")
                        .WithMany("Posts")
                        .HasForeignKey("ForumId")
                        .HasConstraintName("FK_Post_Forum");

                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Post_Users");

                    b.Navigation("Forum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.PostReply", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Post", "Post")
                        .WithMany("PostReplies")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_PostReply_Post");

                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("PostReplies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PostReply_Users");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Tag", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Tags_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.User", b =>
                {
                    b.HasOne("IkapatigiCapstone.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Roles1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Cure", b =>
                {
                    b.Navigation("Diagnostics");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Forum", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.PlantDisease", b =>
                {
                    b.Navigation("Diagnostics");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Post", b =>
                {
                    b.Navigation("PostReplies");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Status", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("HowTos");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.Tag", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("IkapatigiCapstone.Models.User", b =>
                {
                    b.Navigation("AddRequestDiagnostics");

                    b.Navigation("Forums");

                    b.Navigation("HowTos");

                    b.Navigation("PlantDiseases");

                    b.Navigation("PostReplies");

                    b.Navigation("Posts");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
